.github: fixes indentation

diff --git a/.github/workflows/ci-checks.yml b/.github/workflows/ci-checks.yml
--- a/.github/workflows/ci-checks.yml
+++ b/.github/workflows/ci-checks.yml
@@ -8,15 +8,35 @@ jobs:
   ci:
     name: Run CI pipeline.
     runs-on: ubuntu-20.04
+
+    strategy:
+      matrix:
+        python-version: [3.8]
+
     steps:
       - uses: actions/checkout@v2
-      - name: Setup env
-      - run: |
-        apt update && apt install -y python3 python3-pip
-        pip install -r requirements_dev.txt
+
+      - name: Set Up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Install dependencies
+        run: |
+          pip install --upgrade pip
+          pip install -r requirements_dev.txt
+
       - name: Run pre-commit hooks against codebase
         run: |
-        pre-commit install
-        pre-commit run --all-files
+          pre-commit install
+          pre-commit run --all-files
+          if [ $? -ne 0 ]
+          then
+            echo "Pre-commit hooks failed."
+            exit 1
+          else
+            exit 0
+          fi
+
       - name: Run application tests
-      - run: pytest
+        run: pytest
